#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jul 30 14:08:50 2022

@author: kukurihime
"""
import pandas

class CGraph:
    def __init(self, glaphTitle = "no name")__:
        self glaphData = 
    